config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'

  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/xoatheloai/:id/' =>'theloais#destroy' ,as: :xoatheloai
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  get '/user' => 'admin#user'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get '/xoatruyen/:id/' =>'edittruyens#destroy' ,as: :xoatruyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'
  get '/xoabinhluan/:id/' =>'binhluans#destroy' ,as: :xoabinhluan
  get '/search'=>'truyens#search'
  resources :rating
  post '/ratings' => 'ratings#create'
  resources :finalrate
  get '/updaterate/:id' => 'finalrates#updaterate' ,as: :updaterate
  get '/createcolumn/:id' =>'finalrates#create',as: :createcolumn
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/finalrate.rb
class Finalrate < ApplicationRecord
	belongs_to :truyen
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :truyen
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
  belongs_to :theloai
  has_many :binhluans
  has_many :ratings
  has_one :finalrate
  def self.search(search)
     where("name_vn LIKE ?", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/edittruyens_controller.rb
class EdittruyensController < ApplicationController
	def new
    @truyen = Truyen.new
    @theloais=Theloai.all
  end
  def edit
    @theloais=Theloai.all
    @truyen = Truyen.find(params[:id])
  end
  def list
    @theloais=Theloai.all
    @truyens=Truyen.all
  end
  def create
    @truyen = Truyen.new(truyen_params)
    if @truyen.save
      redirect_to createcolumn_path(@truyen.id)
    end
  end
  def update
    @truyen = Truyen.find(params[:id])
    if @truyen.update(truyen_params)
      redirect_to '/edit'
    end
  end
	def destroy
    @truyen = Truyen.find(params[:id])
    @truyen.destroy

    redirect_to edit_path
  end
  private
  def truyen_params
    params.require(:truyen).permit(:name_vn, :name_en, :content_vn, :content_en, :image, :theloai_id,:rate)
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
	  @theloais=Theloai.all
	  @truyens=Truyen.order("updated_at DESC")

	  # CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG view)
	  @average_rate=0
	  @Is_average_rate_int=true
	  @count=0

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/edittruyens_helper.rb
module EdittruyensHelper
end

app/helpers/finalrates_helper.rb
module FinalratesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/edittruyens/edit.html.erb
<div class="section">

<h1>Edit Truyện</h1>
<%= form_for @truyen do |f| %>
<div class="col-sm-8">
  <p>
    <%= f.label :name_vn  %><br>
    <%= f.text_field :name_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :name_en  %><br>
    <%= f.text_field :name_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_vn  %><br>
    <%= f.text_area :content_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_en  %><br>
    <%= f.text_area :content_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :image_url  %><br>
    <%= f.text_field :image ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :theloai_id  %>
    <h5>điền số ứng với thể loại</h5>
    <ol>
      <% @theloais.each do |t|%>
      <li>
        <%=t.title %>
      </li>
      <%end%>
    </ol>
    <br>
    <%= f.text_field :theloai_id ,class: "form-control"%>
  </p>
  <%= f.submit "OK",class: "btn btn-default" %>
</div>
<% end %>
<a href="<%=themtheloai_path%>" class="btn btn-default">cập nhật thêm thể loại</a>
  <a href="<%=home_path%>" class="btn btn-default">về trang chủ</a>
    <a href="<%=uptruyen_path%>" class="btn btn-default">up thêm truyện</a>
      <a href="<%=admin_path%>" class="btn btn-default">Trang Admin</a>
</div>

app/views/edittruyens/list.html.erb
<div class="section">

  <h2>chọn truyện muốn edit</h2>
  <ol>
    <% @truyens.each do |t| %>
    <li>
    	<a href="<%=edittruyen_path(t)%>" class="btn btn-default"><%= t.name_vn %></a>
    	<%= link_to 'DELETE', xoatruyen_path(t), method: :delete ,class: "btn btn-default"%>
    	</li>
    <%end%>
  </ol>
</div>

app/views/edittruyens/new.html.erb
<div class="section">
<h1>up Truyện</h1>
<%= form_for @truyen do |f| %>
<div class="col-sm-8">
  <p>
    <%= f.label :name_vn  %><br>
    <%= f.text_field :name_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :name_en  %><br>
    <%= f.text_field :name_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_vn  %><br>
    <%= f.text_area :content_vn ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :content_en  %><br>
    <%= f.text_area :content_en  ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :image_url  %><br>
    <%= f.text_field :image ,class: "form-control"%>
  </p>
  <p>
    <%= f.label :theloai_id  %>
    <h5>điền số ứng với thể loại</h5>
    <ol>
      <% @theloais.each do |t|%>
      <li>
        <%=t.title %>
      </li>
      <%end%>
    </ol>
    <br>
    <%= f.text_field :theloai_id ,class: "form-control"%>
  </p>
  <%= f.submit "OK",class: "btn btn-default" %>
</div>
<% end %>
<a href="<%=themtheloai_path%>" class="btn btn-default">cập nhật thêm thể loại</a>
  <a href="<%=home_path%>" class="btn btn-default">về trang chủ</a>
    <a href="<%=admin_path%>" class="btn btn-default">Trang Admin</a>
</div>