config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'

  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/xoatheloai/:id/' =>'theloais#destroy' ,as: :xoatheloai
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  get '/user' => 'admin#user'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get '/xoatruyen/:id/' =>'edittruyens#destroy' ,as: :xoatruyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'
  get '/xoabinhluan/:id/' =>'binhluans#destroy' ,as: :xoabinhluan
  get '/search'=>'truyens#search'
  resources :rating
  post '/ratings' => 'ratings#create'
  resources :finalrate
  get '/updaterate/:id' => 'finalrates#updaterate' ,as: :updaterate
  get '/createcolumn/:id' =>'finalrates#create',as: :createcolumn
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/finalrate.rb
class Finalrate < ApplicationRecord
	belongs_to :truyen
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :truyen
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
  belongs_to :theloai
  has_many :binhluans
  has_many :ratings
  has_one :finalrate
  def self.search(search)
     where("name_vn LIKE ?", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
	  @theloais=Theloai.all
	  @truyens=Truyen.order("updated_at DESC")

	  # CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG view)
	  @average_rate=0
	  @Is_average_rate_int=true
	  @count=0

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/finalrates_helper.rb
module FinalratesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/show.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97841360-1', 'auto');
  ga('send', 'pageview');

  </script>

</head>

<body>

  <div class="section">

    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="text-left">
            <i class="fa fa-3x fa-fw fa-book"></i>
            <b>
              <i class="">Truyện Song Ngữ Anh-Việt</i>
            </b>
          </h1>
        </div>
        <div class="row">
          <div class="col-md-12">
            <hr>
          </div>
        </div>
      </div>
    </div>

    <div class="section">
<ul>
  <li>
    <a href="<%=themtheloai_path%>"  class="btn btn-default">cập nhật thêm thể loại</a>
  </li>
  <li>
    <a href="<%=edit_path%>"  class="btn btn-default">Chỉnh Sửa Truyện</a>
  </li>
  <li>
      <a href="<%=uptruyen_path%>"  class="btn btn-default">up thêm truyện</a>
  </li>
  <li>
      <a href="<%=signup_path%>"  class="btn btn-default">dang ky</a>
  </li>
  <li>
      <a href="<%=login_path%>"  class="btn btn-default">dang nhap</a>
  </li>
  <li>
      <a href="<%=home_path%>"  class="btn btn-default">về trang chủ</a>
   </li>
</ul>

</div>
</div>

</body>

</html>

app/views/admin/user.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
</head>
<body>
<div class="section">
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
         <h1>Danh sách user</h1>
            <ul>
              <% @users.each do |t|%>
              <li>
                <div class="col-md-3"><%="first name : #{t.first_name}"%></div>
                <div class="col-md-3"><%="last name : #{t.last_name}"%></div>
                <div class="col-md-3"><%="email : #{t.email}"%></div>
              </li>
              <%end%>
            </ul>
          </div>
         <br/><br/><h1>Danh sách bình luận</h1>
          <div class="col-md-12">
            <ul>
              <% @binhluans.each do |t|%>
              <li>
		<div class="col-md-3"><%="User : #{t.user_id}"%></div>
                <div class="col-md-3"><%="Đã bình luận : #{t.content}"%></div>
                <div class="col-md-3"><%="truyện : #{t.truyen_id}"%></div>
                <%= link_to 'DELETE', xoabinhluan_path(t), method: :delete ,class: "btn btn-default"%>
              </li>
              <%end%>
            </ul>
          </div>
        </div>
      </div>
    </div>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FAM-Truyện Song Ngữ</title>
  <link rel="icon" type="image/gif" href="http://www.freeiconspng.com/uploads/book-stack-icon--icon-search-engine-16.png" />
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<style>
  .font{
    font-family: "Comic Sans MS", cursive, sans-serif;
  }
</style>

</head>

<body>
  <div class="navbar navbar-default navbar-fixed-top navbar-static-top font">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><span>Brand</span></a>
      </div>
      <div class="collapse navbar-collapse font" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active">
            <a href="<%= home_path %>">Trang Chủ<i class="fa fa-border fa-home pull-left"></i></a>
          </li>
          <li>
            <a href="<%= new_path %>">Truyện Mới Cập Nhật</a>
          </li>
          <li>
            <a href="<%= all_path %>">Tất Cả Các Truyện</a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
            aria-expanded="false">Thể Loại<br><i class="fa fa-caret-down pull-right"></i></a>
            <ul class="dropdown-menu" role="menu">
              <% @theloais.each do |t|%>
              <li>
                <a href="<%= theloai_path(t) %>"><%= t.title%></a>
              </li>
              <%end%>
            </ul>
          </li>
        </ul>
      </div>
        </div>
      </div>
      <div class="navbar navbar-default navbar-fixed-top navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="navbar-ex-collapse">
            <ul class="nav navbar-left navbar-nav">
              <li class="active">
                <a href="<%= home_path %>">Trang chủ<i class="fa fa-border fa-home pull-left"></i></a>
              </li>
              <li>
                <a href="<%= new_path %>">Truyện mới cập nhật</a>
              </li>
              <li>
                <a href="<%= all_path %>">Tất cả các truyện</a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-expanded="false">Thể loại<br><i class="fa fa-caret-down pull-right"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <% @theloais.each do |t|%>
                  <li>
                    <a href="<%= theloai_path(t) %>"><%= t.title%></a>
                  </li>
                  <%end%>
                </ul>
              </li>
              <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-expanded="false"><%= current_user.last_name %> <%= current_user.first_name %><br><i class="fa fa-caret-down pull-right"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="<%= logout_path%>">Đăng xuất</a>"</li>
                </ul>
              </li>
            </ul>
            <% else %>
          </ul>
          <% end %>
        </ul>
        <%= form_tag(search_path, :method => "get", id: "search-form" ,class: "navbar-form navbar-right text-left") do %>
        <div class="form-group font">
          <%= text_field_tag :search, params[:search],class: "form-control" , :placeholder => "Tìm Kiếm"%>
        </div>
        <button type="submit" class="btn btn-default font">Tìm Truyện</button>
        <%end%>
        <p class="navbar-right navbar-text">Truyện Song Ngữ
          <br>
        </p>
        <% if current_user %>
        <% else %>
        <a class="btn btn-default navbar-btn navbar-left" data-toggle="modal" href="<%=login_path%>"><i class="fa fa-star fa-fw"></i>Đăng Nhập</a>
        <%end%>
      </div>
    </div>
  </div>

  <%= yield %>

</body>
</html>