config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'

  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/xoatheloai/:id/' =>'theloais#destroy' ,as: :xoatheloai
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  get '/user' => 'admin#user'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get '/xoatruyen/:id/' =>'edittruyens#destroy' ,as: :xoatruyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'
  get '/xoabinhluan/:id/' =>'binhluans#destroy' ,as: :xoabinhluan
  get '/search'=>'truyens#search'
  resources :rating
  post '/ratings' => 'ratings#create'
  resources :finalrate
  get '/updaterate/:id' => 'finalrates#updaterate' ,as: :updaterate
  get '/createcolumn/:id' =>'finalrates#create',as: :createcolumn
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/finalrate.rb
class Finalrate < ApplicationRecord
	belongs_to :truyen
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :truyen
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
  belongs_to :theloai
  has_many :binhluans
  has_many :ratings
  has_one :finalrate
  def self.search(search)
     where("name_vn LIKE ?", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
	  @theloais=Theloai.all
	  @truyens=Truyen.order("updated_at DESC")

	  # CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG view)
	  @average_rate=0
	  @Is_average_rate_int=true
	  @count=0

  end
end

app/controllers/theloais_controller.rb
class TheloaisController < ApplicationController
  def show
    @theloais=Theloai.all
    @theloai = Theloai.find(params[:id])
    @truyens = @theloai.truyens

    # CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG view)
    @average_rate=0
    @Is_average_rate_int=true
    @count=0

  end
  def new
    @theloai = Theloai.new
    @theloais=Theloai.all
  end
  def create
    @theloai = Theloai.new(theloai_params)
    if @theloai.save
      redirect_to '/themtheloai'
    end
  end
  def destroy
    @theloai = Theloai.find(params[:id])
    @theloai.destroy

    redirect_to themtheloai_path
  end
  private
  def theloai_params
    params.require(:theloai).permit(:title)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/edittruyens_helper.rb
module EdittruyensHelper
end

app/helpers/finalrates_helper.rb
module FinalratesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/theloais/new.html.erb
<div class="section">
<h1>Thêm thể loại</h1>
<h3>các thể loại hiện có</h3>
<ol>
  <% @theloais.each do |t|%>
  <li>
    <%=t.title %>
    <%= link_to 'DELETE', xoatheloai_path(t), method: :delete ,class: "btn btn-default"%>
  </li>
  <%end%>
</ol>
<%= form_for(@theloai) do |f| %>
<div class="col-sm-8">
  <p>
    <%= f.label :title  %><br>
    <%= f.text_field :title ,class: "form-control"%>
  </p>
  <%= f.submit "Thêm",class: "btn btn-default" %>
</div>
<%end%>
<a href="<%=uptruyen_path%>" class="btn btn-default">up thêm truyện</a>
  <a href="<%=home_path%>" class="btn btn-default">về trang chủ</a>
  </div>

app/views/theloais/show.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97841360-1', 'auto');
  ga('send', 'pageview');

  </script>
</head>

<body>
  <body>
    
    <div class="section">

      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h1 class="text-left">
              <i class="fa fa-3x fa-fw fa-book"></i>
              <b>
                <i>Truyện Song Ngữ Anh-Việt</i>
              </b>
            </h1>
          </div>
          <div class="row">
            <div class="col-md-12">
              <hr>
            </div>
            <h1 class="lead" align="center"><%=@theloai.title%></h1>
          </div>
        </div>
      </div>

      <% @truyens.each do |t|%>
      <div class="section">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <a href="<%=truyen_path(t)%>" title="<%= truncate t.content_vn, length: 400 %>"><img src="<%=t.image%>"
                class="img-responsive"></a>
              </div>
              <div class="col-md-3">
                <h1 align="center"><a href="<%=truyen_path(t)%>" title="<%= truncate t.content_vn, length: 400 %>"><%= t.name_vn %></a></h1>
                <p align="justify"><%= truncate t.content_vn, length: 200 %></p>
              </div>
              <div class="col-md-3">
                <h1 align="center"><a href="<%=truyen_path(t)%>" title="<%= truncate t.content_vn, length: 400 %>"><%= t.name_en %></a></h1>
                <p align="justify"><%= truncate t.content_en, length: 200 %></p>
              </div>
            <div class="col-md-2">
              <p align="center">
                <p>Cập Nhật</p>
                <p><%="#{time_ago_in_words(t.updated_at.in_time_zone(7))} ago"%></p>
              </p>

                <!-- CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG CONTROLLER)-->
                <% @average_rate=t.ratings.average(:rate) %>
                <% @rating_num=t.ratings.count %>
                <% if @rating_num != 0 and @average_rate != nil %>
                <% @Is_average_rate_int=(@average_rate -@average_rate.to_i)>0?false : true %>
                <% @count=@average_rate.to_i %>
                <% if @Is_average_rate_int %>
                <% @count=@average_rate %>
                <% end %>
                <% end %>

                <div class="row">
                <br>
                  <% if @rating_num != 0 %>

                   <!--HIEN THI SAO TUONG UNG VOI DIEM -->

                  <%if @Is_average_rate_int %>
                  <% for i in 1..@count do %>
                  <img src="https://raw.githubusercontent.com/wazery/ratyrate/master/lib/generators/ratyrate/templates/star-on.png"/>
                  <%end%>
                  <%=" (#{@average_rate} / 5)"%>
                  <%else%>
                  <% for i in 1..@count do %>
                  <img src="https://raw.githubusercontent.com/wazery/ratyrate/master/lib/generators/ratyrate/templates/star-on.png"/>
                  <%end%>
                  <img src="https://raw.githubusercontent.com/wazery/ratyrate/master/lib/generators/ratyrate/templates/star-half.png"/>
                  <%=" (#{@average_rate} / 5)"%>
                  <%end%>
                  <%else%>
                  <p>Chưa có lượt đánh giá nào</p>
                  <%end%>
                </div>
                </p>
                </div>
            </div>
          </div>
        </div>
        <%end%>

        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <hr>
            </div>
            <p>FAM-Truyện Song Ngữ</p>
          </div>
        </div>

    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1 class="text-center">FAM</h1>
            <p class="text-center">We are a group of University of Engineering and Technology
              <br>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-1">
            <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
            class="img-circle img-responsive">
          </div>
          <div class="col-md-2">
            <h3 class="text-left">Ngô Hải Yến</h3>
            <p class="text-left">K60-CD</p>
          </div>
          <div class="col-md-1">
            <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
            class="img-circle img-responsive">
          </div>
          <div class="col-md-2">
            <h3 class="text-left">Bùi Diệu Linh</h3>
            <p class="text-left">K60-CB</p>
          </div>
          <div class="col-md-1">
            <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
            class="img-circle img-responsive">
          </div>
          <div class="col-md-2">
            <h3 class="text-left">Đinh Khắc Quý</h3>
            <p class="text-left">K60-CAC
              <br>
            </p>
          </div>
          <div class="col-md-1">
            <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png"
            class="img-circle img-responsive">
          </div>
          <div class="col-md-2">
            <h3 class="text-left">Vũ Hoàng Long</h3>
            <p class="text-left">K60-CAC</p>
          </div>
        </div>
      </div>
    </div>

      </div>

    </body>
</body>
</html>